Sprint 5
svetlana-ananina/qa_python_5 pull request #1
Opened 2023-11-10 08:40 UTC by svetlana-ananina

Финальный проект спринта 5 в ветке dev

2023-11-12 09:00 UTC, kadirovgm requested changes

2023-11-12 09:00 UTC, kadirovgm commented on README.md
> +
отлично!

2023-11-12 09:00 UTC, kadirovgm commented on conftest.py
> +def open_main_window():
нужно исправить: давай переименуем эту фикстуру, это фикстура, которая делает setup и teardown для нашего теста, так что open_main_window - некорректное название, скорее я бы назвал - driver

2023-11-12 09:00 UTC, kadirovgm commented on conftest.py
> +    driver.get(url.MAIN_PAGE_URL)
молодец! что вынесла тестовые статичные URL в отдельный файл

2023-11-12 09:00 UTC, kadirovgm commented on conftest.py
> +    return driver
нужно исправить: методы с 12 по 42 строки - это не фикстуры, а скорее helper-методы, фикстура - это методы которые могут быть выполнены перед тестом или после теста (как preconditions), а просто чтобы какие то данные передавать ими не стоит пользоваться, лучше сделать обычными функциями, а не декораторами

нужно перенести функции эти из файла conftest.py в helpers.py

2023-11-12 09:00 UTC, kadirovgm commented on data.py
> +class DATA:
отлично!

2023-11-12 09:00 UTC, kadirovgm commented on helpers.py
> +def sign_in(driver, login, password):
нужно исправить: вот это можно перевести в фикстуру)

2023-11-12 09:00 UTC, kadirovgm commented on helpers.py
> +    elements = helpers.find_elements(driver, loc.MAIN_PAGE_ORDER_BUTTON)
нужно исправить: лучше разделять методы и тесты, здесь у тебя метод авторизации, он не должен себя же сам проверять, для этого есть тесты, которые должны вызывать методы, а потом проверять их, так что эту часть лучше оставить в самом тесте как assert

2023-11-12 09:00 UTC, kadirovgm commented on tests/test_authorization_page.py
> +        """ Проверка регистрации с главной страницы через кнопку "Войти в аккаунт" """
супер! молодец, что подписываешь тесты докстрингом

2023-11-12 09:00 UTC, kadirovgm commented on tests/test_authorization_page.py
> +    def test_auth_from_main_page_login_button(self, register_new_user):
отлично! хорошие тесты

2023-11-12 09:00 UTC, kadirovgm commented on urls.py
> +class URLS:
супер!

2023-11-12 09:00 UTC, kadirovgm commented on tests/test_registration_page.py
> +        driver.quit()
нужно исправить: лучше пользоваться общей фикстурой, которая открывает и закрывает браузер сама, в твоем случае она описана как `open_main_window`

2023-11-13 14:18 UTC, kadirovgm approved these changes

2023-11-13 22:33 UTC, merged

2023-11-13 22:57 UTC, svetlana-ananina commented on helpers.py
> +def sign_in(driver, login, password):
А как можно передать параметры в фикстуру?